#!/usr/bin/env python3
"""
Build js/transcripts.js from transcript files in transcripts/youtube/.

Scans for .en.txt files and creates a mapping of episode number -> filename
so the frontend can fetch transcripts on demand.
"""

import os
import re
import json
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
TRANSCRIPTS_DIR = REPO_ROOT / "transcripts" / "youtube"
OUTPUT_FILE = REPO_ROOT / "js" / "transcripts.js"

# Pattern: ep{number}_{youtubeId}.en.txt
FILENAME_PATTERN = re.compile(r"^ep(\d+)_(.+)\.en\.txt$")


def build_transcript_map():
    transcript_map = {}

    for filename in sorted(os.listdir(TRANSCRIPTS_DIR)):
        match = FILENAME_PATTERN.match(filename)
        if match:
            ep_num = match.group(1)
            transcript_map[ep_num] = filename

    return transcript_map


def write_js(transcript_map):
    js_content = (
        "// Transcript file mapping - auto-generated by scripts/build_transcripts.py\n"
        f"// {len(transcript_map)} transcripts available\n"
        f"const TRANSCRIPT_MAP = {json.dumps(transcript_map, indent=2)};\n"
    )
    OUTPUT_FILE.write_text(js_content)
    print(f"Wrote {len(transcript_map)} transcript mappings to {OUTPUT_FILE}")


if __name__ == "__main__":
    transcript_map = build_transcript_map()
    write_js(transcript_map)
